-- اضافه کردن فیلدهای جدید
ALTER TABLE properties 
ADD COLUMN IF NOT EXISTS bedrooms INT DEFAULT 0 COMMENT 'تعداد خواب',
ADD COLUMN IF NOT EXISTS max_tenants INT DEFAULT 0 COMMENT 'حداکثر تعداد مستاجر',
ADD COLUMN IF NOT EXISTS mortgage_price DECIMAL(15,2) DEFAULT 0 COMMENT 'قیمت رهن',
ADD COLUMN IF NOT EXISTS rent_price DECIMAL(15,2) DEFAULT 0 COMMENT 'قیمت اجاره',
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT '' COMMENT 'تلفن',
ADD COLUMN IF NOT EXISTS mobile VARCHAR(20) DEFAULT '' COMMENT 'تلفن همراه',
ADD COLUMN IF NOT EXISTS owner_phone VARCHAR(20) DEFAULT '' COMMENT 'تلفن مالک',
ADD COLUMN IF NOT EXISTS tenant_phone VARCHAR(20) DEFAULT '' COMMENT 'تلفن مستاجر',
ADD COLUMN IF NOT EXISTS owner_name VARCHAR(100) DEFAULT '' COMMENT 'نام مالک';

