-- اضافه کردن فیلدهای جدید برای امکانات
ALTER TABLE properties 
ADD COLUMN IF NOT EXISTS has_water BOOLEAN DEFAULT FALSE COMMENT 'آب',
ADD COLUMN IF NOT EXISTS has_electricity BOOLEAN DEFAULT FALSE COMMENT 'برق',
ADD COLUMN IF NOT EXISTS has_gas BOOLEAN DEFAULT FALSE COMMENT 'گاز',
ADD COLUMN IF NOT EXISTS has_phone BOOLEAN DEFAULT FALSE COMMENT 'تلفن',
ADD COLUMN IF NOT EXISTS has_cabinet BOOLEAN DEFAULT FALSE COMMENT 'کابینت',
ADD COLUMN IF NOT EXISTS has_water_heater BOOLEAN DEFAULT FALSE COMMENT 'آبگرمکن',
ADD COLUMN IF NOT EXISTS has_cooler BOOLEAN DEFAULT FALSE COMMENT 'کولر',
ADD COLUMN IF NOT EXISTS has_carpet BOOLEAN DEFAULT FALSE COMMENT 'موکت',
ADD COLUMN IF NOT EXISTS has_ceramic BOOLEAN DEFAULT FALSE COMMENT 'سرامیک',
ADD COLUMN IF NOT EXISTS has_paint BOOLEAN DEFAULT FALSE COMMENT 'نقاشی',
ADD COLUMN IF NOT EXISTS has_radiator BOOLEAN DEFAULT FALSE COMMENT 'شوفاژ',
ADD COLUMN IF NOT EXISTS has_video_intercom BOOLEAN DEFAULT FALSE COMMENT 'آیفون تصویری',
ADD COLUMN IF NOT EXISTS has_antenna BOOLEAN DEFAULT FALSE COMMENT 'آنتن مرکزی',
ADD COLUMN IF NOT EXISTS has_remote_door BOOLEAN DEFAULT FALSE COMMENT 'درب ریموت دار',
ADD COLUMN IF NOT EXISTS has_package BOOLEAN DEFAULT FALSE COMMENT 'پکیج',
ADD COLUMN IF NOT EXISTS has_hidden_light BOOLEAN DEFAULT FALSE COMMENT 'نور مخفی';

-- تغییر type از ENUM به VARCHAR برای پشتیبانی از چند نوع معامله
ALTER TABLE properties MODIFY COLUMN type VARCHAR(50) NOT NULL COMMENT 'نوع معامله (ممکن است چند مورد باشد با جداکننده کاما)';

